### ISSUE TITLE
timeshift 스냅샷이 없는 PC 에서 오류

### ISSUE THREAD

**Issue by chaeya** [hamonikr/hamonikr-pcchecker#6]
timeshift 스냅샷이 없는 PC의 경우 아래와 같은 오류가 나면서 실행되지 않습니다.

```
gufw                                            install
ufw                                             install
False
Traceback (most recent call last):
  File "/usr/local/bin/pcchecker", line 506, in <module>
    Application().run()
  File "/usr/local/bin/pcchecker", line 354, in __init__
    print(os.listdir(ts_path))
FileNotFoundError: [Errno 2] 그런 파일이나 디렉터리가 없습니다: '/timeshift/snapshots
```

**Comment by yeji0407** [comment]
말씀해 주신 오류를 수정하여 프로젝트를 업데이트 하였습니다. 아래는 변경사항을 업데이트 한 저장소 주소입니다.
 https://github.com/2020-Invesum-Internship/hamonikr-pcchecker

저장소의 이슈 등록을 활성화 하였으니 앞으로도 많은 기여 부탁드립니다. 감사합니다.
